# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 754fb8b053dfe9e39853ffc00bacbae22125c8ee9a9aac2bc5a447b23579674480417ac512120f55921649f1662d3d0aed84d4010872a2beeca010155a8d5d02

test:
  secret_key_base: 00ca9c2aea9cf7c29a8a49903eaa94707581b2385041e8540a558cf2ae71d5b981193e4d8a0122b80dd579d548ad064fcdb76fb08b5f29b60b00b3ba88942a78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
